"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Activity, ArrowUpRight, Heart, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";

const donations = [
  ["Brawn", "$1,000", "Clean Water Initiative", "2 minutes ago"], ["Philip", "$600", "Education Fund", "4 minutes ago"], ["Sarah M.", "$50", "Emergency Relief", "7 minutes ago"], ["Anonymous", "$250", "Food Security", "9 minutes ago"], ["Amara K.", "$120", "Girls in STEM", "12 minutes ago"], ["The Northstar Fund", "$4,500", "Climate Resilience", "15 minutes ago"], ["Luis R.", "$75", "Maternal Health", "18 minutes ago"], ["Anonymous", "$30", "Emergency Relief", "21 minutes ago"], ["Maya & Co.", "$850", "Clean Water Initiative", "25 minutes ago"], ["Derek P.", "$200", "Education Fund", "28 minutes ago"]
];

export function LiveDonationFeed() {
  const [visible, setVisible] = useState(donations.slice(0, 4));
  useEffect(() => { const timer = window.setInterval(() => setVisible((current) => [donations[Math.floor(Math.random() * donations.length)], ...current].slice(0, 4)), 7000); return () => window.clearInterval(timer); }, []);
  return <section id="transparency" className="bg-white px-5 py-20 dark:bg-emerald-950/40 lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-emerald-700 dark:text-amber-300"><Activity size={15} /> Real-time generosity</div><h2 className="font-display text-4xl tracking-[-.03em] sm:text-5xl">A movement you can see.</h2><p className="mt-5 max-w-md leading-7 text-ink-500 dark:text-white/60">Every contribution tells a story. Our live ledger makes the collective force of generosity visible, minute by minute.</p><div className="mt-8 flex items-center gap-3 text-sm font-semibold"><span className="grid size-9 place-items-center rounded-full bg-amber-100 text-amber-600"><Sparkles size={16} /></span> $2,418,930 given this year</div><a href="#transparency" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-emerald-700 dark:text-amber-300">View our transparency report <ArrowUpRight size={16} /></a></div><div className="rounded-[2rem] border border-emerald-900/10 bg-[#f7faf8] p-4 shadow-soft dark:border-white/10 dark:bg-emerald-950 sm:p-6"><div className="mb-3 flex items-center justify-between px-2 text-xs font-bold uppercase tracking-[.16em] text-ink-500"><span>Latest gifts</span><span className="flex items-center gap-2 text-emerald-700 dark:text-emerald-300"><span className="size-2 animate-pulse rounded-full bg-emerald-500" /> Live</span></div><div className="space-y-2"><AnimatePresence initial={false}>{visible.map((item, index) => { const large = item[1].includes("1,000") || item[1].includes("4,500"); return <motion.div key={`${item[0]}-${item[1]}-${index}`} initial={{ opacity: 0, y: -18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, height: 0 }} className={`flex items-center gap-3 rounded-2xl p-4 ${large ? "bg-amber-50 ring-1 ring-amber-200 dark:bg-amber-400/10 dark:ring-amber-300/20" : "bg-white dark:bg-white/5"}`}><div className="grid size-10 shrink-0 place-items-center rounded-full bg-emerald-100 font-display text-sm text-emerald-800 dark:bg-emerald-900 dark:text-emerald-100">{item[0][0]}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{item[0]} <span className="font-normal text-ink-500">gave to</span> {item[2]}</div><div className="mt-1 text-xs text-ink-500">{item[3]}</div></div><div className="text-right"><div className="font-display text-lg text-emerald-800 dark:text-amber-300">{item[1]}</div><Heart size={14} className="ml-auto mt-1 text-emerald-400" fill="currentColor" /></div></motion.div>; })}</AnimatePresence></div></div></div></section>;
}
