"use client";

import { motion } from "framer-motion";
import { Quote, Star } from "lucide-react";

const testimonials = [
  ["HopeBridge is the most transparent charity I have ever donated to. I can see exactly where my money goes, and the updates feel genuinely human.", "Michael R.", "Monthly donor", "https://i.pravatar.cc/100?img=12"],
  ["The water project changed the rhythm of our whole village. Our children are in school instead of walking for hours to find water.", "Amina O.", "Community leader", "https://i.pravatar.cc/100?img=47"],
  ["Our partnership works because HopeBridge brings rigor without losing the human story. Their reporting gives our team real confidence.", "Elena V.", "Corporate partner", "https://i.pravatar.cc/100?img=32"],
  ["I started with one small gift during an emergency. The follow-through and reporting turned it into a monthly commitment.", "James K.", "Emergency donor", "https://i.pravatar.cc/100?img=68"],
  ["The mentorship fund gave me the confidence and tools to apply for university. Someone I will never meet decided my future mattered.", "Nia T.", "Scholarship recipient", "https://i.pravatar.cc/100?img=49"],
  ["HopeBridge makes it easy to bring our whole office into giving. We see the outcomes, celebrate the wins, and keep learning together.", "Priya S.", "People & culture lead", "https://i.pravatar.cc/100?img=25"]
];

export function Testimonials() { return <section id="stories" className="bg-[#edf5f1] px-5 py-20 dark:bg-emerald-950 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><div className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-emerald-700 dark:text-amber-300">Shared belief</div><h2 className="font-display text-4xl tracking-[-.03em] sm:text-5xl">What our community says.</h2></div><div className="flex items-center gap-3 rounded-full bg-white px-4 py-3 shadow-sm dark:bg-white/10"><div className="font-display text-2xl">4.9</div><div><div className="flex gap-0.5 text-amber-500">{Array.from({ length: 5 }).map((_, i) => <Star key={i} size={14} fill="currentColor" />)}</div><div className="mt-1 text-[11px] text-ink-500 dark:text-white/50">Based on 2,340 reviews</div></div></div></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{testimonials.map((item, index) => <motion.article whileHover={{ y: -4 }} key={item[1]} className="flex flex-col rounded-3xl bg-white p-6 shadow-sm dark:bg-white/10"><div className="flex items-center justify-between"><div className="flex gap-0.5 text-amber-500">{Array.from({ length: 5 }).map((_, i) => <Star key={i} size={14} fill="currentColor" />)}</div><Quote size={23} className="text-emerald-200 dark:text-emerald-700" /></div><p className="mt-6 flex-1 font-display text-lg leading-7 text-emerald-950 dark:text-white/90">“{item[0]}”</p><div className="mt-7 flex items-center gap-3 border-t border-emerald-900/10 pt-5 dark:border-white/10"><img src={item[3]} alt="" className="size-10 rounded-full object-cover" /><div><div className="text-sm font-bold">{item[1]}</div><div className="text-xs text-ink-500 dark:text-white/50">{item[2]}</div></div></div></motion.article>)}</div></div></section>; }
